name: stock
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - matplotlib==3.3.1
  - pandas==1.1.0
  - python==3.8.5
  - requests==2.24.0
  - scikit-learn==0.23.2
  - flask==1.1.2
  - joblib=0.16.0
  - pip:
      - requests-html
      - yahoo-fin
      - google-cloud-storage
      - google-api-python-client
      - google-auth
      - google-auth-httplib2